---
title: "My english activity log"
---

From now on, you will use this article to include every single activity that you do in English in a chronological order (e.g. reading a book in English, watching TV shows and series in English, going to an English Evening in Mons, travelling to an English-speaking country, playing games in English such as the pretty exciting game LyricsTraining, etc.). You can even write a few lines about what you’ve watched/read/done and recommend certain things to your friends. The sky’s the limit! We value personal initiative and we will be happy to read whatever you have to offer.


|     |     |
| --- | --- |
| 16/09 to ? | **One strange rock**, 7/10 episodes done |
| 19/09 to ? | Serie **Peaky blinders** in VO (season 1-2-3 done) |
| 30/09 | Lyricstraining : Bohemian Rhapsody and I Want To Break Free **Queen** |
| 08/10 | Lyricstraining : (I Can't Get No) Satisfaction **The Rolling Stones** |
| 24/10 | Reading an article about car technology |
| 20/11 | **Behind the flood** a documentary with Leonardo Di Caprio |
| 28/11 | Watching videos about fish of the genus *Betta* for the futur purpose of having an aquarium with a couple of *Betta Mahachaiensis* |
| 06/12 | Lyricstraining : Dance Monkey |
