---
title: "Conclusion"
description: 
author:
  - name: Verschaetse Corentin
    url: {}
date: 04-20-2020
preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Coral reefs are among the most diverse and productive ecosystems that exist on Earth. Moreover, they are very important for many kinds of reasons. 

First of all, reefs are a habitat for many marine species. And the most of ocean’s diversity is in the reefs because coral reefs are a great source of nutrients for marine food chains. Hence their importance.

Secondly, these ecosystems carry out the fixation of carbon and nitrogen. At present, it is not negligible.

Furthermore, we must not forget that these ecosystems contribute to the protection of coasts by reducing the amplitude of the waves. Especially during storms during which waves store so much energy that they become devastating.

Fortunately, all these major roles performed by coral reefs are known by scientists who are trying to conserve these beautiful ecosystems. But before acting, scientists need to understand how they really work. That is why Romina King and her crew developed a technology to make high definition pictures of the see floor. Other scientists study the causes of bleaching events and the effects of microplastics. And it is not just climate change that impact corals. We, human, have a direct effect on corals by our agriculture.

With all these knowledge, other scientists have already started to act. With the technology of the 3D-print, some scientists are recreating reefs. But will that be enough? There is still a lot to do and understand on corals reefs. Will we be able to save them before it is too late ?
