---
title: "Introduction"
description: 
author:
  - name: Verschaetse Corentin
    url: {}
date: 04-16-2020
preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the Earth’s history, there have already been several climatic changes. With periods of glaciation and warming. These changes have been caused by small variations on the Earth’s orbit which influenced the quantity of solar energy on the Earth.

Today, everybody agrees that currently, climate is changing. And it is most certainly our fault, the fault of the Human.

For us, Human, a heat increase of a few degrees doesn't matter to us. But for sensitive living organisms or ecosystems, like coral reefs, it is a huge threat. These organisms are adapted to a stable environment. If they are sudden variations, they are not able to adapt in such a short time and may therefor even disappear completely from the Earth’s surface. That’s what is happening now for many species. According to the IUCN (The International Union for Conservation of Nature), more than 31.000 species are in danger of extinction. We have a role to play!  That’s why we have to do our utmost to protect these species which are suffering from our acts. 

This portfolio is focused on coral reefs, that are organisms which are clearly impacted by climate changes. Corals are fragile animals, which are living under the threat of the rise of temperature and the acidification of oceans. With these variations of their environment, corals can expel their symbiotics algae. This phenomenon is called “bleaching events” because with this expulsion, they become white. The bleaching is bad for corals because it is the algae that give their nutrients. If the perturbations of the environment last too long, corals will irremediably die.

So, to conserve these fabulous ecosystems, scientists develop several innovative technics to protect, maintain or recreate these unique ecosystems.
